### ISSUE TITLE
Can't resolve 'vuejs-oauth2-discord` in vue/client/src

### ISSUE THREAD

**Issue by N1GHTR4NG3R** [ForgeOfficial/vuejs-oauth2-discord#2]
I ran `npm install vuejs-oauth2-discord` inside my server folder - and i tried importing it into client/src/main.js

I presume I either have to import it twice into client/server respectively, or install it outside of both folders and inside the main global folder.

Side note, unrelated
Could you also create a complete example of a components page - Thanks

**Comment by ForgeOfficial** [comment]
Hey,

_> I presume I either have to import it twice into client/server respectively_
**Yes**
